CREATE DATABASE QuanLyQuanCaFe
GO
USE QuanLyQuanCaFe
GO
--food
--table
--danhmucdoan
--TK
--hoadon
--thongtinhoadon
CREATE TABLE BAN
(
	id INT IDENTITY PRIMARY KEY,
	name NVARCHAR(100) NOT NULL,
	state NVARCHAR(100) NOT NULL DEFAULT N'Trống'--trống||có người
)
GO
CREATE TABLE TK
(
	id INT IDENTITY PRIMARY KEY,
	
	UserName NVARCHAR(100)NOT NULL,
	Password NVARCHAR(100)NOT NULL,
	
)
GO
CREATE TABLE DANHMUCDOAN
(
	id INT IDENTITY PRIMARY KEY,
	name NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE Food
(
	id INT IDENTITY PRIMARY KEY,
	name NVARCHAR(100) NOT NULL,
	idCategory INT NOT NULL,
	price FLOAT NOT NULL
)
GO
CREATE TABLE HOADON
(
	id INT IDENTITY PRIMARY KEY,
	DatecheckIn DATE NOT NULL,
	DatecheckOut DATE,
	idTable INT NOT NULL,
	state INT NOT NULL--1 đã thanh toán||0 là chưa
)
GO
CREATE TABLE THONGTINHOADON
(	
	id INT IDENTITY PRIMARY KEY,
	idHOADON INT NOT NULL,
	idFood INT NOT NULL,
	count INT NOT NULL DEFAULT 0

	FOREIGN KEY (idHOADON) REFERENCES dbo.HOADON(id),
	FOREIGN KEY (idFood) REFERENCES dbo.Food(id)
)
GO


